const nav = [ ['about.html','고또마케팅'], ['services.html','하는 일'], ['location.html','오시는 길'] ];
const serviceNav = [['blog','브랜드 블로그'],['hpblog','홈페이지형 블로그'],['instagram','인스타그램'],['place','플레이스'],['daangn','당근마켓'],['cafe','카페 바이럴'],['website','홈페이지 제작']];
export const arrow = '<svg viewBox="0 0 32 32" fill="none" aria-hidden="true"><path d="M6 26 26 6M6 6h20v20" stroke="currentColor" stroke-width="1.4"/></svg>';
export function renderHeader(page) {
  return `<a class="skip-link" href="#main">본문 바로가기</a>
  <header class="site-header"><a href="index.html" class="wordmark" aria-label="고또마케팅 홈">kotto<span>고또마케팅</span></a><nav class="desktop-nav" aria-label="주요 메뉴">${nav.map(([href,label])=>`<a href="${href}" ${page===href?'aria-current="page"':''}>${label}</a>`).join('')}<a class="nav-contact" href="contact.html" ${page==='contact.html'?'aria-current="page"':''}>상담 문의 ${arrow}</a></nav><button class="menu-open" type="button" data-menu-open aria-expanded="false" aria-haspopup="dialog" aria-controls="site-menu" aria-label="전체 메뉴 열기"><span class="menu-label">메뉴</span><span class="menu-lines" aria-hidden="true"><i></i><i></i></span></button></header><noscript><nav class="no-script-nav" aria-label="주요 메뉴"><a href="index.html">홈</a><a href="about.html">고또마케팅</a><a href="services.html">하는 일</a><a href="contact.html">상담 문의</a><a href="location.html">오시는 길</a></nav></noscript>
  <dialog id="site-menu" class="site-menu" aria-labelledby="menu-title"><div class="menu-top"><a class="wordmark" href="index.html" aria-label="고또마케팅 홈">kotto</a><p id="menu-title">고또마케팅 살펴보기</p><button type="button" data-menu-close aria-label="전체 메뉴 닫기">닫기 <span aria-hidden="true">×</span></button></div><div class="menu-content"><nav class="menu-chapters" aria-label="전체 메뉴"><a href="index.html">처음으로</a><a href="about.html">고또마케팅</a><a href="services.html">하는 일</a><a href="contact.html">상담 문의</a><a href="location.html">오시는 길</a></nav><nav class="menu-services" aria-label="서비스 상세"><p>안경원을 알리는 방법</p>${serviceNav.map(([key,label])=>`<a href="service-${key}.html">${label}<span aria-hidden="true">↗</span></a>`).join('')}</nav></div><div class="menu-bottom"><span>안경원 전문 광고·콘텐츠 마케팅</span><a href="mailto:communication@kotto.kr">communication@kotto.kr</a></div></dialog>`;
}
export function renderFooter() {
  return `<footer class="site-footer"><div class="footer-invite"><p>어떤 이야기를 전하고 싶으신가요?</p><a class="footer-heading" href="contact.html"><span>안경원 이야기를<br>들려주세요.</span>${arrow}</a></div><div class="footer-links"><div><a class="wordmark" href="index.html" aria-label="고또마케팅 홈">kotto</a><p>안경원 전문 광고·콘텐츠 마케팅</p></div><nav aria-label="연락처"><a href="mailto:communication@kotto.kr">communication@kotto.kr</a><a href="https://open.kakao.com/o/sBj11zAf" target="_blank" rel="noopener noreferrer">카카오톡 문의 ↗</a><a href="https://m.blog.naver.com/kottorai" target="_blank" rel="noopener noreferrer">고또마케팅 블로그 ↗</a></nav><nav aria-label="사이트 안내"><a href="about.html">고또마케팅</a><a href="services.html">전체 서비스</a><a href="location.html">오시는 길</a></nav></div><div class="footer-legal"><p>세모기획 · 대표 고강일 · 사업자등록번호 791-07-02592<br>경기도 남양주시 순화궁로 249 파라곤스퀘어 M동 1528호</p><p>© KOTTO MARKETING</p><button type="button" data-top aria-label="페이지 맨 위로">맨 위로 ↑</button></div></footer>`;
}
